import { processDocumentPipeline } from '../services/extraction.service.js';
import { askDocumentQuestion } from '../services/gemini.service.js';
import { documentService } from '../services/documentService.js';
import { SAMPLE_DOCUMENTS } from '../services/sampleDocuments.js';

export const documentController = {
  // POST /api/documents/upload
  async uploadDocument(req, res) {
    try {
      const userId = req.user.id;

      // Handle preset sample demo
      if (req.body && req.body.sampleKey && SAMPLE_DOCUMENTS[req.body.sampleKey]) {
        const sample = SAMPLE_DOCUMENTS[req.body.sampleKey];
        const savedDoc = await documentService.processAndSaveDocument({
          userId,
          originalFileName: `${req.body.sampleKey}_sample.pdf`,
          fileType: 'application/pdf',
          rawAnalysis: sample,
        });

        return res.status(201).json({
          success: true,
          aiAnalyzed: false,
          isDemo: true,
          message: 'Sample document loaded successfully',
          document: savedDoc,
        });
      }

      // Safe diagnostic logging
      console.log('--- Document Upload & Analysis Pipeline ---');
      console.log(`[Diagnostic] File received: ${req.file ? 'yes' : 'no'}`);
      if (req.file) {
        console.log(`[Diagnostic] Mime type: ${req.file.mimetype}`);
        console.log(`[Diagnostic] File size: ${req.file.size} bytes`);
      }

      // Handle uploaded file
      if (!req.file) {
        return res.status(400).json({
          success: false,
          aiAnalyzed: false,
          error: 'No file was received',
          message: 'Please provide a valid PDF, JPG, or PNG document or choose a demo preset.',
        });
      }

      if (!req.file.buffer || req.file.buffer.length === 0) {
        return res.status(400).json({
          success: false,
          aiAnalyzed: false,
          error: 'Empty file received',
          message: 'The uploaded file buffer has 0 bytes.',
        });
      }

      console.log('[Diagnostic] Gemini request started');
      const result = await processDocumentPipeline({
        fileBuffer: req.file.buffer,
        mimeType: req.file.mimetype,
        fileName: req.file.originalname,
        userId,
      });
      console.log('[Diagnostic] Gemini response received & pipeline executed');

      return res.status(201).json({
        success: true,
        aiAnalyzed: true,
        message: 'Document analyzed and validated successfully',
        document: result.rawRecord || result,
      });
    } catch (err) {
      console.error('[Diagnostic] Upload pipeline failed:', err.message);
      return res.status(500).json({
        success: false,
        aiAnalyzed: false,
        error: err.message || 'Document Analysis Failed',
        message: err.message || 'An error occurred during AI extraction and validation.',
      });
    }
  },

  // GET /api/documents/demo-sample
  async getDemoSample(req, res) {
    try {
      const sample = SAMPLE_DOCUMENTS.tax_notice;
      const {
        runDeterministicValidation,
        normalizeDeadlines,
        normalizeRisks,
        normalizeActions,
      } = await import('../services/validation.service.js');

      const normalizedDeadlines = normalizeDeadlines(sample.deadlines || []);
      const validationResults = runDeterministicValidation(sample);
      const { finalLevel, risks: normalizedRisks } = normalizeRisks(
        sample.risks || [],
        validationResults,
        normalizedDeadlines
      );
      const normalizedActions = normalizeActions(
        sample.actions || [],
        normalizedDeadlines,
        validationResults
      );

      const demoDoc = {
        id: 'demo-sample-tax-notice',
        user_id: req.user.id,
        is_demo: true,
        source: 'Sample / Demo Data',
        source_note: 'Sample / Demo Data — Pre-computed reference scenario for presentation reliability (Not generated by Gemini)',
        document_type: sample.documentType,
        document_title: sample.documentTitle,
        issuer: sample.issuer,
        language: sample.language || 'en',
        summary: sample.summary,
        key_fields: sample.keyFields,
        amounts: sample.amounts,
        dates: sample.dates,
        deadlines: normalizedDeadlines,
        risks: normalizedRisks,
        actions: normalizedActions,
        explanation: sample.explanation,
        validation_results: validationResults,
        processing_status: 'completed',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };

      // Ensure stored so chat works on this demo document ID
      await documentService.processAndSaveDocument({
        userId: req.user.id,
        originalFileName: 'tax_notice_demo.pdf',
        fileType: 'application/pdf',
        rawAnalysis: demoDoc,
      });

      return res.json({ document: demoDoc });
    } catch (err) {
      console.error('Error serving demo sample:', err.message);
      return res.status(500).json({ error: 'Failed to retrieve demo sample' });
    }
  },

  // GET /api/documents
  async listDocuments(req, res) {
    try {
      const documents = await documentService.getUserDocuments(req.user.id);
      return res.json({ documents });
    } catch (err) {
      console.error('Error listing documents:', err.message);
      return res.status(500).json({ error: 'Failed to retrieve documents' });
    }
  },

  // GET /api/documents/:id
  async getDocument(req, res) {
    try {
      const doc = await documentService.getDocumentById(req.params.id, req.user.id);
      if (!doc) {
        return res.status(404).json({ error: 'Document not found' });
      }

      // Verify document belongs to authenticated user
      if (doc.user_id && doc.user_id !== req.user.id && !req.user.id.startsWith('demo-user')) {
        return res.status(403).json({ error: 'Forbidden', message: 'You do not have permission to view this document.' });
      }

      return res.json({ document: doc });
    } catch (err) {
      console.error('Error retrieving document:', err.message);
      return res.status(500).json({ error: 'Failed to retrieve document' });
    }
  },

  // DELETE /api/documents/:id
  async deleteDocument(req, res) {
    try {
      const doc = await documentService.getDocumentById(req.params.id, req.user.id);
      if (!doc) {
        return res.status(404).json({ error: 'Document not found or already deleted' });
      }

      if (doc.user_id && doc.user_id !== req.user.id && !req.user.id.startsWith('demo-user')) {
        return res.status(403).json({ error: 'Forbidden', message: 'You do not have permission to delete this document.' });
      }

      const success = await documentService.deleteDocument(req.params.id, req.user.id);
      return res.json({ success: true, message: 'Document deleted successfully' });
    } catch (err) {
      console.error('Error deleting document:', err.message);
      return res.status(500).json({ error: 'Failed to delete document' });
    }
  },

  // POST /api/documents/:id/chat
  async chatWithDocument(req, res) {
    try {
      const { message } = req.body;
      const { id } = req.params;

      if (!message || !message.trim()) {
        return res.status(400).json({ error: 'Message text is required' });
      }

      const doc = await documentService.getDocumentById(id, req.user.id);
      if (!doc) {
        return res.status(404).json({ error: 'Document not found' });
      }

      // Verify document belongs to authenticated user
      if (doc.user_id && doc.user_id !== req.user.id && !req.user.id.startsWith('demo-user')) {
        return res.status(403).json({ error: 'Forbidden', message: 'You do not have permission to access this document.' });
      }

      // Fetch existing conversation history
      const history = await documentService.getChatHistory(id, req.user.id);

      // Save user question
      await documentService.addChatMessage({
        documentId: id,
        userId: req.user.id,
        role: 'user',
        message: message.trim(),
      });

      // Query Gemini grounded with document context
      const reply = await askDocumentQuestion({
        documentData: doc,
        chatHistory: history,
        question: message.trim(),
      });

      // Save assistant response
      await documentService.addChatMessage({
        documentId: id,
        userId: req.user.id,
        role: 'assistant',
        message: reply,
      });

      // Return updated history
      const updatedHistory = await documentService.getChatHistory(id, req.user.id);

      return res.json({
        reply,
        history: updatedHistory,
      });
    } catch (err) {
      console.error('Error in chatWithDocument:', err.message);
      return res.status(500).json({ error: 'Failed to process document question' });
    }
  },

  // GET /api/documents/:id/chat
  async getChatHistory(req, res) {
    try {
      const history = await documentService.getChatHistory(req.params.id, req.user.id);
      return res.json({ history });
    } catch (err) {
      console.error('Error fetching chat history:', err.message);
      return res.status(500).json({ error: 'Failed to fetch chat history' });
    }
  },
};
