import { supabaseAdmin, isSupabaseConfigured } from '../config/supabase.js';
import {
  runDeterministicValidation,
  normalizeDeadlines,
  normalizeRisks,
  normalizeActions,
} from './validation.service.js';
import { SAMPLE_DOCUMENTS } from './sampleDocuments.js';

// In-Memory store for offline / demo mode
const memoryDocuments = new Map();
const memoryChat = new Map();

// Pre-seed demo documents so Dashboard and Document Result have instant data for testing
function seedDemoData() {
  const demoUserId = 'demo-user-00000000-0000-0000-0000-000000000001';

  Object.entries(SAMPLE_DOCUMENTS).forEach(([key, sample], index) => {
    const id = `demo-doc-${index + 1}`;
    const normalizedDeadlines = normalizeDeadlines(sample.deadlines || []);
    const validationResults = runDeterministicValidation(sample);
    const { finalLevel, risks: normalizedRisks } = normalizeRisks(
      sample.risks || [],
      validationResults,
      normalizedDeadlines
    );
    const normalizedActions = normalizeActions(
      sample.actions || [],
      normalizedDeadlines,
      validationResults
    );

    memoryDocuments.set(id, {
      id,
      user_id: demoUserId,
      original_file_name: `${key}_sample.pdf`,
      file_type: 'application/pdf',
      document_type: sample.documentType,
      document_title: sample.documentTitle,
      issuer: sample.issuer,
      language: sample.language || 'en',
      summary: sample.summary,
      key_fields: sample.keyFields,
      amounts: sample.amounts,
      dates: sample.dates,
      deadlines: normalizedDeadlines,
      risks: normalizedRisks,
      actions: normalizedActions,
      explanation: sample.explanation,
      validation_results: validationResults,
      processing_status: 'completed',
      created_at: new Date(Date.now() - index * 86400000 * 2).toISOString(),
      updated_at: new Date(Date.now() - index * 86400000 * 2).toISOString(),
    });
  });

  // Also seed dedicated hackathon demo scenario under fixed ID 'demo-sample-tax-notice'
  const taxSample = SAMPLE_DOCUMENTS.tax_notice;
  const taxDeadlines = normalizeDeadlines(taxSample.deadlines || []);
  const taxVal = runDeterministicValidation(taxSample);
  const { finalLevel: taxRisk, risks: taxRisks } = normalizeRisks(taxSample.risks || [], taxVal, taxDeadlines);
  const taxActions = normalizeActions(taxSample.actions || [], taxDeadlines, taxVal);

  memoryDocuments.set('demo-sample-tax-notice', {
    id: 'demo-sample-tax-notice',
    user_id: demoUserId,
    is_demo: true,
    source: 'Sample / Demo Data',
    source_note: 'Sample / Demo Data — Pre-computed reference scenario for presentation reliability (Not generated by Gemini)',
    original_file_name: 'tax_notice_demo.pdf',
    file_type: 'application/pdf',
    document_type: taxSample.documentType,
    document_title: taxSample.documentTitle,
    issuer: taxSample.issuer,
    language: 'en',
    summary: taxSample.summary,
    key_fields: taxSample.keyFields,
    amounts: taxSample.amounts,
    dates: taxSample.dates,
    deadlines: taxDeadlines,
    risks: taxRisks,
    actions: taxActions,
    explanation: taxSample.explanation,
    validation_results: taxVal,
    processing_status: 'completed',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  });
}

seedDemoData();

export const documentService = {
  async processAndSaveDocument({ userId, originalFileName, fileType, rawAnalysis }) {
    // 1. Normalize deadlines
    const normalizedDeadlines = normalizeDeadlines(rawAnalysis.deadlines || []);

    // 2. Run deterministic validation engine
    const validationResults = rawAnalysis.validation_results || runDeterministicValidation(rawAnalysis);

    // 3. Normalize risks & actions
    const { finalLevel, risks: normalizedRisks } = normalizeRisks(
      rawAnalysis.risks || [],
      validationResults,
      normalizedDeadlines
    );

    const normalizedActions = normalizeActions(
      rawAnalysis.actions || [],
      normalizedDeadlines,
      validationResults
    );

    // 4. Prepare document record
    const docData = {
      user_id: userId,
      original_file_name: originalFileName,
      file_type: fileType,
      document_type: rawAnalysis.documentType || 'General Document',
      document_title: rawAnalysis.documentTitle || originalFileName,
      issuer: rawAnalysis.issuer || 'Unknown Issuer',
      language: rawAnalysis.language || 'en',
      summary: rawAnalysis.summary || '',
      key_fields: rawAnalysis.keyFields || rawAnalysis.key_fields || {},
      amounts: rawAnalysis.amounts || [],
      dates: rawAnalysis.dates || [],
      deadlines: normalizedDeadlines,
      risks: normalizedRisks,
      actions: normalizedActions,
      explanation: rawAnalysis.explanation || '',
      validation_results: validationResults,
      processing_status: 'completed',
      updated_at: new Date().toISOString(),
    };

    // 5. Persist to Supabase if available
    if (isSupabaseConfigured && supabaseAdmin) {
      try {
        const { data, error } = await supabaseAdmin
          .from('documents')
          .insert([docData])
          .select()
          .single();

        if (!error && data) {
          return data;
        }
      } catch (err) {
        console.warn('Falling back to memory storage after Supabase error:', err.message);
      }
    }

    // Fallback: In-memory store
    const id = `doc-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;
    const saved = {
      id,
      ...docData,
      created_at: new Date().toISOString(),
    };
    memoryDocuments.set(id, saved);
    return saved;
  },

  async getUserDocuments(userId) {
    if (isSupabaseConfigured && supabaseAdmin) {
      try {
        const { data, error } = await supabaseAdmin
          .from('documents')
          .select('*')
          .eq('user_id', userId)
          .order('created_at', { ascending: false });

        if (!error && data) {
          return data;
        }
      } catch (err) {
        console.warn('Supabase select error, using memory fallback:', err.message);
      }
    }

    // Memory store fallback
    const list = [];
    for (const doc of memoryDocuments.values()) {
      if (doc.user_id === userId || userId.startsWith('demo-user')) {
        list.push(doc);
      }
    }
    return list.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
  },

  async getDocumentById(id, userId) {
    if (isSupabaseConfigured && supabaseAdmin) {
      try {
        const { data, error } = await supabaseAdmin
          .from('documents')
          .select('*')
          .eq('id', id)
          .single();

        if (!error && data) {
          return data;
        }
      } catch (err) {
        console.warn('Supabase get error, checking memory:', err.message);
      }
    }

    return memoryDocuments.get(id) || null;
  },

  async deleteDocument(id, userId) {
    if (isSupabaseConfigured && supabaseAdmin) {
      try {
        const { error } = await supabaseAdmin
          .from('documents')
          .delete()
          .eq('id', id)
          .eq('user_id', userId);

        if (!error) return true;
      } catch (err) {
        console.warn('Supabase delete error:', err.message);
      }
    }

    const doc = memoryDocuments.get(id);
    if (doc) {
      memoryDocuments.delete(id);
      memoryChat.delete(id);
      return true;
    }
    return false;
  },

  async addChatMessage({ documentId, userId, role, message }) {
    if (isSupabaseConfigured && supabaseAdmin) {
      try {
        const { data, error } = await supabaseAdmin
          .from('chat_messages')
          .insert([{
            document_id: documentId,
            user_id: userId,
            role,
            message,
          }])
          .select()
          .single();

        if (!error && data) return data;
      } catch (err) {
        console.warn('Supabase chat insert error:', err.message);
      }
    }

    // Memory chat fallback
    const id = `msg-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`;
    const msgObj = {
      id,
      document_id: documentId,
      user_id: userId,
      role,
      message,
      created_at: new Date().toISOString(),
    };

    if (!memoryChat.has(documentId)) {
      memoryChat.set(documentId, []);
    }
    memoryChat.get(documentId).push(msgObj);
    return msgObj;
  },

  async getChatHistory(documentId, userId) {
    if (isSupabaseConfigured && supabaseAdmin) {
      try {
        const { data, error } = await supabaseAdmin
          .from('chat_messages')
          .select('*')
          .eq('document_id', documentId)
          .order('created_at', { ascending: true });

        if (!error && data) return data;
      } catch (err) {
        console.warn('Supabase chat get error:', err.message);
      }
    }

    return memoryChat.get(documentId) || [];
  },

  async getDashboardStats(userId) {
    const docs = await this.getUserDocuments(userId);
    const totalDocuments = docs.length;

    let highRiskCount = 0;
    let upcomingDeadlinesCount = 0;
    let overdueDocumentsCount = 0;
    const now = new Date();

    docs.forEach((doc) => {
      // High risk determination
      const risks = doc.risks || [];
      const validationStatus = doc.validation_results?.status;
      const isHigh = risks.some((r) => r.level === 'HIGH') || validationStatus === 'FAIL';
      if (isHigh) {
        highRiskCount++;
      }

      // Deadline checks
      let hasOverdue = false;
      const deadlines = doc.deadlines || [];
      deadlines.forEach((dl) => {
        if (dl.status === 'OVERDUE') {
          hasOverdue = true;
        } else if (dl.status === 'UPCOMING') {
          upcomingDeadlinesCount++;
        } else if (dl.date) {
          const d = new Date(dl.date);
          if (!isNaN(d.getTime())) {
            if (d < now) {
              hasOverdue = true;
            } else {
              upcomingDeadlinesCount++;
            }
          }
        }
      });

      if (hasOverdue) {
        overdueDocumentsCount++;
      }
    });

    return {
      totalDocuments,
      highRiskDocuments: highRiskCount,
      upcomingDeadlines: upcomingDeadlinesCount,
      overdueDocuments: overdueDocumentsCount,
      recentDocuments: docs.slice(0, 5),
    };
  },
};
