import React from 'react';
import { Link } from 'react-router-dom';
import RiskBadge from './RiskBadge';
import StatusBadge from './StatusBadge';
import { formatDate } from '../utils/formatters';

export default function DocumentHeader({ document, onDelete, activeTab, onTabChange }) {
  if (!document) return null;

  const title = document.document_title || document.documentTitle || document.original_file_name;
  const docType = (document.document_type || document.documentType || 'General Document').toUpperCase();
  const issuer = (document.issuer || 'N/A').toUpperCase();
  const createdDate = document.created_at;

  const highestRisk = document.overallRisk ||
    ((document.risks || []).find((r) => r.level === 'HIGH')
      ? 'HIGH'
      : (document.risks || []).find((r) => r.level === 'MEDIUM')
      ? 'MEDIUM'
      : 'LOW');

  return (
    <div className="space-y-6">
      {/* Top Nav & Tab Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[#D5CEC1]">
        <Link
          to="/dashboard"
          className="font-mono text-xs uppercase tracking-widest text-[#70716D] hover:text-[#101B2D] transition-colors"
        >
          ← BACK TO DASHBOARD
        </Link>

        <div className="flex items-center gap-3">
          {/* Editorial Tab Switcher */}
          <div className="flex border border-[#D5CEC1] bg-[#FAF8F2]">
            <button
              onClick={() => onTabChange('analysis')}
              className={`px-4 py-2 font-mono text-xs uppercase tracking-wider transition-colors ${
                activeTab === 'analysis'
                  ? 'bg-[#101B2D] text-[#F1EBDD] font-bold'
                  : 'text-[#101B2D] hover:bg-[#E8E0D2]'
              }`}
            >
              01 ANALYSIS
            </button>

            <button
              onClick={() => onTabChange('chat')}
              className={`px-4 py-2 font-mono text-xs uppercase tracking-wider border-l border-[#D5CEC1] transition-colors ${
                activeTab === 'chat'
                  ? 'bg-[#101B2D] text-[#F1EBDD] font-bold'
                  : 'text-[#101B2D] hover:bg-[#E8E0D2]'
              }`}
            >
              02 ASK DOCUMENT
            </button>
          </div>

          {onDelete && (
            <button
              onClick={onDelete}
              title="Delete Document"
              className="px-3 py-2 border border-[#D5CEC1] hover:border-[#8B2626] font-mono text-xs text-[#70716D] hover:text-[#8B2626] transition-colors"
            >
              DELETE
            </button>
          )}
        </div>
      </div>

      {/* Prominent Demo Notice if Sample */}
      {document.is_demo && (
        <div className="p-4 border border-[#9A6B2F] bg-[#9A6B2F]/10 font-mono text-xs text-[#101B2D] flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <span className="font-bold text-[#9A6B2F] uppercase tracking-wider">
              [ SAMPLE / DEMO DATA ]
            </span>
            <span>Pre-verified scenario. Demonstrates deterministic validation and action planning.</span>
          </div>
          <span className="text-[10px] text-[#70716D] uppercase">
            NOT GENERATED BY GEMINI IN REAL-TIME
          </span>
        </div>
      )}

      {/* Main Document Title & Metadata Block */}
      <div className="border border-[#D5CEC1] bg-[#FAF8F2] p-6 sm:p-10 space-y-6">
        <div>
          <span className="font-mono text-[11px] text-[#3158A8] uppercase tracking-widest block mb-2">
            05 — DOCUMENT
          </span>
          <h1 className="font-serif text-3xl sm:text-5xl font-bold tracking-tight text-[#101B2D]">
            {title}
          </h1>
        </div>

        {/* Ruled Metadata Bar */}
        <div className="pt-4 border-t border-[#D5CEC1] flex flex-wrap items-center justify-between gap-4 font-mono text-xs">
          <div className="flex flex-wrap items-center gap-4 sm:gap-6 text-[#70716D]">
            <span>TYPE: <strong className="text-[#101B2D]">{docType}</strong></span>
            <span>ISSUER: <strong className="text-[#101B2D]">{issuer}</strong></span>
            <span>DATE: <strong className="text-[#101B2D]">{formatDate(createdDate)}</strong></span>
          </div>

          <div className="flex items-center gap-3">
            <RiskBadge level={highestRisk} />
            <StatusBadge status={document.processing_status} />
          </div>
        </div>
      </div>
    </div>
  );
}

